CREATE TYPE geschlecht AS ENUM ('MAENNLICH', 'WEIBLICH', 'DIVERS');
CREATE TYPE mitgliedsstatus AS ENUM ('AKTIV', 'INAKTIV');

CREATE TABLE IF NOT EXISTS mitglied (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
    version         INTEGER NOT NULL DEFAULT 0,
    vorname         TEXT NOT NULL,
    nachname        TEXT NOT NULL,
    email           TEXT NOT NULL UNIQUE,
    geburtsdatum    DATE,
    telefonnummer   TEXT UNIQUE,
    geschlecht      geschlecht,
    mitgliedsstatus mitgliedsstatus,
    beitrittsdatum  DATE,
    interessen      JSONB,
    erzeugt         TIMESTAMP NOT NULL,
    aktualisiert    TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS mitglied_nachname_idx ON mitglied(nachname);

CREATE TABLE IF NOT EXISTS ausweis (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
    ausstellungsdatum   DATE NOT NULL,
    ablaufdatum         DATE NOT NULL,
    mitglied_id         INTEGER NOT NULL UNIQUE REFERENCES mitglied ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ausweis_mitglied_id_idx ON ausweis(mitglied_id);

CREATE TABLE IF NOT EXISTS ausleihe (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
    ausleihdatum    DATE NOT NULL,
    rueckgabedatum  DATE NOT NULL,
    mitglied_id     INTEGER NOT NULL REFERENCES mitglied ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ausleihe_mitglied_id_idx ON ausleihe(mitglied_id);

